### ISSUE TITLE
HQM - Completed requests remain as "Unclaimed Reward"

### ISSUE THREAD

**Issue by WTFGeeks** [WTFGeeks/Natural-Magic#1]
This is a known HQM issue and does not affect game play although slightly annoying. https://bitbucket.org/Newcastlegeek/hqm-bugtracker/issue/87/quests-remaining-unclaimed-reward

**Comment by Skyllian** [comment]
haha.... thanks for the heads up _smile_

i almost wanted to report it

**Comment by WTFGeeks** [comment]
This is now fixed in v0.7.
