### ISSUE TITLE
Day bloom Dissapear

### ISSUE THREAD

**Issue by shadow1moon** [WTFGeeks/Natural-Magic#10]
In a garden biome Dayblooms planted on long grass blocks will randomly disappear after an unknown amount of time.

**Comment by Unthinker** [comment]
Just started playing tonight and figured I'd get started on Botania. While in a Forest biome all 12 of my Dayblooms disappeared but the Nightshade and Hydroangea are all still present. So doesn't seem to be only in the Gardens.

Edit: Scratch that the Nightshade and the first Hydroangea I placed also disappeared. Not exactly sure on timing but it had to have happened in the last 45 minutes.

**Comment by shadow1moon** [comment]
Yeah, I was starting with Botania too. Now all my work is for nothing, because I was gonna let them run while i started with Magic Crops. 
I havent seen anything "Plant" related vanish not related to Botania, So i believe it is only related to those flowers.

**Comment by WTFGeeks** [comment]
This is not a bug, it's a config designed so that passive generating flora decay after so long.  This is designed to make the player explore better routes of generating flora, instead of sticking with very inefficient flora such as dayblooms.
