### ISSUE TITLE
I Feel Great! Fire Resistance Potion

### ISSUE THREAD

**Issue by AdzeMarschall** [WTFGeeks/Natural-Magic#101]
Not sure if this is just me, is a bug or is intentional. During this quest, you are told to make a fire resistance (3:00) potion; doing so using the standard magma cream recipe did not work for me, I had to make a fire resistance (8:00) potion and then use glowstone dust to remake a fire resistance (3:00). The standard way and the glowstone dust way both yield the same potion, but they have different item ID's ( 373:8195 and 373:8227 respectively) and only the 373:8227 will make the quest complete. 

As I said, not sure if this is intentional, feel free to call me a fool!

**Comment by WTFGeeks** [comment]
I'll have this changed in the next update, it's tricky with potions and HQM as when you edit the HQM book it doesn't show the sub ID values of potions, so I have a 50/50 chance of getting the right one, at least I know it's the other one this time, you'll notice further on in the book It starts giving you botania potions that's the reason why.

**Comment by AdzeMarschall** [comment]
I can imagine HQM is a pain to configure right with sub ID's. Thanks for the update, I'll keep playing and let you if I find anything else. Nice work btw, amazing pack.

**Comment by ArcticHowler** [comment]
I can't remember which version this post was made during, but in 0.7.3 I'm unable to even get regeneration (2:00) to register and as there's no way to upgrade it and then downgrade it, I'm at a crossroads, ignore it and wait for a fix, or go wild and make a crap ton of the same potions over and over again until it recognizes it... the only potion that it accepted(I have yet to try upgrading and downgrading the fire resistance potion) was the splash healing II.
