### ISSUE TITLE
Not sure if bug or planned

### ISSUE THREAD

**Issue by BronyfromOz** [WTFGeeks/Natural-Magic#102]
Accidentally at first then intentionally cast Feather Touch + Dig (Ars Magica) on a Pure Daisy (Botania) and the Daisy just disappeared.

**Comment by TheMudpit** [comment]
I have also heard in tutorial videos that you mustn't use tinkers tools to move a botania flower or they sometimes disappear. Just thought I'd mention it, botania flowers seem to be a bit moody. Tinkers tools too - they don't seem to like witchery tool protection poppets - I had a lumber axe disappear out my hand. Anytime you use one mod on another, it's a bit of a roll of the dice it seems - just so many variables. (Nice idea for a spell by the way, I love ars magica - if only they could stop the spell books disappearing when you die, and having to re-create all the spells!)

**Comment by WTFGeeks** [comment]
The reason for this is botania flowers basically break twice before the flower drops, the reason behind this is for items such as the drum of the wild so it doesn't break your gen/func flora when you use it. So when you use another mods tool or spell that's designed to instantly break something, it counts the first break but not the second so the item is not dropped. It's a design decision on Botania's end. I'll speak to vaz about it but I very much doubt this will be changed as you can't design mods around other mods all the time. As for Ars Magica it's a state at the minute and Mithion knows this, he has promised one last update to hopefully fix all known issues before he leaves the MC modding community.
