### ISSUE TITLE
technical problems

### ISSUE THREAD

**Issue by facux3** [WTFGeeks/Natural-Magic#104]
Can you tell me why I can not technically move when I log my world? I can only perform just 1 movement every minute or more :( and the loading time when opening the game with the Atlauncher is about f5 minutes... what is wrong? my computer or any mod?
please help me
PD: sorry for my bad english but I'm latin :P

**Comment by BronyfromOz** [comment]
That doesn't sound good.  I load the game in about 1 minute and I load the world in 10 seconds on my laptop.  What are your computer's technical specifications?

**Comment by facux3** [comment]
yes It doesn't sound goog :/ I have a laptop with this specifications

processor pentium 2.00ghz
windows 7 64bits
2gb ram
intel HD Graphics Family

I know it is not a good computer but normally minecraft goes well

**Comment by BronyfromOz** [comment]
That looks OK.  Have you checked the RAM allocation in the AT Launcher?  Try to up the RAM used.

**Comment by facux3** [comment]
this are the values:

initial memory/ram: 256mb

maximum memoryRam: 512Mb

what values do I have to put?

**Comment by BronyfromOz** [comment]
Try initial 512 and maximum 1024.  Or even higher if you have the option.

**Comment by facux3** [comment]
ok I'll try that... I hope it doesn't crash my pc xD

**Comment by facux3** [comment]
It didn't work!! T.T

**Comment by BronyfromOz** [comment]
I think the graphics card may be the problem.  Just not powerful enough.  Have you played any other Mod packs before?

**Comment by facux3** [comment]
no mod packs... but I've played with a baunch of mods, so you think is my graphic card?

**Comment by BronyfromOz** [comment]
Maybe, the forums say the graphics card is the main source of lag. Try a crazy pack like the Yogscast Complete pack see if you have the same problem.

**Comment by facux3** [comment]
ok I will try... but for the moment i have disabled around 30 mods and the game is running fine... it's stills spending around 5 minutes for launching the game and around 1 minute for loading the world... but at least I can play :P
