### ISSUE TITLE
Botania Dayblooms and Hydrangous Flowers Disapearing

### ISSUE THREAD

**Issue by Pokecraft12346** [WTFGeeks/Natural-Magic#106]
Whenever I log out of my world and close the game the flowers are there, but the next time I log in THEIR GONE Someone please help, there's nothing anywhere about this happening.

**Comment by WTFGeeks** [comment]
yes any passive generating flower in Natural Magic is set to die off, so the player cannot rely on them forever. You can change this in the Botania config file if you would like.
