### ISSUE TITLE
Efreet's Flame (Thaumic Tinkerer) appears ineffectual.

### ISSUE THREAD

**Issue by BronyfromOz** [WTFGeeks/Natural-Magic#107]
After crafting and equipping the Efreet's Flame focus on my Gold capped Greatwood Wand when I right click if gives the animation of drawing Vis.
No beam, no fire, no diggy diggy hole.

**Comment by MimsyMan** [comment]
But it doesn't diggy diggy hole, it smelts certain placed blocks. Try using it on sand or cobblestone. (Not a lot of uses fer that one)

**Comment by BronyfromOz** [comment]
Oh, wow, what a waste of Foci.
