### ISSUE TITLE
Quest Glitch

### ISSUE THREAD

**Issue by DarkPhoenix86** [WTFGeeks/Natural-Magic#108]
In "Tools of the Trade" under Dwarven Tinkers, When crafting blank patterns, 5 patterns are required, but when crafting you get a stack of 4 and it only registers as 1 in the book.

**Comment by ArcticHowler** [comment]
some of the quests require that you craft it a certain number of times, not that you have that many of the item...

**Comment by WTFGeeks** [comment]
I'll get it changed in the next update, pretty much all the next update will be is a questing update, expect it in a week.
