### ISSUE TITLE
Items not despawning

### ISSUE THREAD

**Issue by 14mal02** [WTFGeeks/Natural-Magic#11]
When items are dropped on the ground (when they are able to be picked up), they will stay there perpetually, not despawning after the normal 5 minutes of being loaded

**Comment by WTFGeeks** [comment]
This is not a bug, I'v enabled it for mods such as Botania that use dropping items on the ground as a core mechanic. The rule is items within a 35 block radius of a player will not de spawn until the player leaves that 35 block radius.
