### ISSUE TITLE
journey map from new update

### ISSUE THREAD

**Issue by ikurah** [WTFGeeks/Natural-Magic#110]
basically i have the file its asking for in the right location but after i click the "I've Downloaded This File" button it makes me download the file again like i didnt have it

**Comment by Skyllian** [comment]
got the same prob. and if i look in the file (where you place the downloaded file) its gone no mather what i try if you click I've Downloaded This File then its gone again

**Comment by ikurah** [comment]
yeah i also tried having the files in both places it wanted it to be still it just poofs into thin air

**Comment by ikurah** [comment]
well i found a work around for it if u guys wanna use the journey map style. just download the map pack with out any of the minimaps, go to your instances and click on the edit mods button on the natural magic section, click on "Add Mod" and find where u have journey map downloaded for mod type just select "mods folder", after that click on the check box for the journey map mod and click on "Enable Mod" and poof load up your game and there you go you now have journey map install and working perfectly. 
- Have fun!

**Comment by Shurhaian** [comment]
The problem is that the download is giving a different version than the installer is looking for. If you rename the downloaded file to what the installer wants, this is another viable workaround.

**Comment by WTFGeeks** [comment]
Unfortunately when journey map updates or changes download location which it has multiple times lately it'll throw off the installer, It'll be changed to the 5.0.1 update in the next version. This will probably be an issue that crops up now and then as, I can't control when the author updates and as he does not allow it to be added to mod packs makes it very awkward, this is why I made opis the recommended map mod although I personally prefer journey map. When this happens the easiest way to solve it is download the pack with Opis, once downloaded delete Opis and add journey map very straightforward and easy to do.
