### ISSUE TITLE
Lapis not spawning at surface like other ores

### ISSUE THREAD

**Issue by Shurhaian** [WTFGeeks/Natural-Magic#111]
I'm not sure if this is a bug or working as intended, to be honest, but - lapis is the only vanilla overworld substance I haven't been able to find on the surface. Since gold, redstone, and even diamond are there, this is conspicuous.

I noticed that in config\cofh\world\Vanilla.json, the other things mentioned have maxHeight=128, but lapis is maxVariance=128. Possible mistype? It seems like a sensible stat, but doesn't seem to be making any lapis appear on the surface. (I don't know how that file format works in detail, so can't say how variance is supposed to work.)

If this is as intended, great, but I didn't see anything about it and it's a fairly odd thing to have so hard to find. The TiCon ores at least tend to be fairly easy to get, not being greatly depth-dependent.

**Comment by kiomadoushi** [comment]
I've found lapis on a pillar atop a high snowy plateau, and in surface caves (above sea level). Might just be bad luck on your part to find so few...

**Comment by Shurhaian** [comment]
Amazingly bad, then. I've never found so much as a single piece without digging deep for it. Ah, well; a counterexample is enough to prove to me that it CAN spawn high.
