### ISSUE TITLE
Ars Magica 2 essence not transfering

### ISSUE THREAD

**Issue by Pokecraft12346** [WTFGeeks/Natural-Magic#116]
So I try to make a self heal spell which needs 500 essence, so I get all of the components and stuff all of the requirements are met for the spell, so then the part that needs the essence comes and thers essence in the obelisk, I link the crafting alter and the obelisk, and heres the weird part, it transfers 100 essence and then just refuses to transfer any more, plz halp

**Comment by WTFGeeks** [comment]
This is a known issue on the AM2 github (https://github.com/Mithion/ArsMagica2/issues?page=1&q=is%3Aopen+is%3Aissue) I would recommend reading through there before going to into AM2 as there is currently a load of issues with it, hopefully the dev will fix these soon.
