### ISSUE TITLE
Ars Magica 2 - No moonstone fall

### ISSUE THREAD

**Issue by poul54** [WTFGeeks/Natural-Magic#117]
Hello,

 In Ars Magica 2, never falling moonstone meteors.

Can u fix it?

**Comment by WTFGeeks** [comment]
What magic level are you? you need to be a minimum of 10 before meteors can spawn also these are the statistics on meteors falling:
1.) Meteors only fall very rarely to begin with (1/100000 chance per tick)
2.) Once a meteor falls, it is 2 in-game days before another even has a chance to fall
these are from Mithion, so they are extremely rare.

Failing that I would check the ars magica 2 github before getting to deep in to AM2 as it is very broken at the minute. Mithion has promised one last update to fix all known issues, before he leaves the modding community.

**Comment by poul54** [comment]
just lvl 10. I gona leveling a bit more and just wait the next update.

thnx
