### ISSUE TITLE
Ars Magica and Thaumcraft

### ISSUE THREAD

**Issue by Logthar** [WTFGeeks/Natural-Magic#118]
Hi,
I recently started playing your modpackage with a friend on my proper server and I was quite happy with it but suddently some issues came up...
The first one is that we can't put any books in the lecture in the crafting altar... The altar is surely build correct, the centerblock (craftingaltarblock) changed it's skin to the witchwood. 
I hope you can help me fixing this problems, so Ars Magica isn't useless for me anymore.
Furthermore, I can't open the UI of the wands by pressing "F", I havn't changed any controls, it's still on default. I can't put any of them on.
Hope you can help me with my second problem too and that any problems will come up later on.

Log

**Comment by WTFGeeks** [comment]
Hi Log 

What type of book are you using? there's a known AM2 issue with certain book at the minute. I would also suggest reading through the AM2 github before going to deep into it, currently it's littered with nasty bugs, hopefully the dev will fix these in the next version (https://github.com/Mithion/ArsMagica2/issues?page=1&q=is%3Aopen+is%3Aissue). For the second problem all you need to do is change your key binding, it looks like with the latest Sanguimancy version it has added a key binding to F called locate players, just change that to something else then it will work fine.

**Comment by Logthar** [comment]
What book do you exactly mean? The writtenbook or another one?
I changed the binding but it's still not working...

**Comment by WTFGeeks** [comment]
whatever book you're trying to place in the lecturn, looking on the AM2 github there's many cases of people having this exact issue. The only way around I'v seen is to use a book and quill also manually signing it yourself as the instant signing mechanic in AM2 is currently broken.

**Comment by Logthar** [comment]
Ah, ok, thanks a lot, and the problem of thaumcraft is now fixed too! thx a lot ;)
