### ISSUE TITLE
Meteorite fire resistance not being applied

### ISSUE THREAD

**Issue by ArcticHowler** [WTFGeeks/Natural-Magic#119]
Not sure what modpack these two are from, but I was wearing a full set of that fire resistance armor from falling meteors and the fire kept burning indefinately, died twice, and since sometimes when you die from fire a gravestone doesn't get place I'm not even sure if my stuff is there anymore, given that I can't advance without going into the nether and I had all of my stuff on me when I went in there to check things out, I am basically forced to restart that world if it is indeed gone... tbh, both of them looked like mobs from doom, but I thought those were removed due to a conflict? either way, the fire doesn't go out even when wearing fire resistance gear, luckily the damage reduction was somewhat working, but I still ended up dead from the fire...

**Comment by WTFGeeks** [comment]
cheers I'll have a look into the fire resistance not being applied.

**Comment by ArcticHowler** [comment]
Luckily when I loaded the world back up, there was in fact a gravestone(it spawned into the wall where a cave was nearby) but the Behemoth didn't do the indefinite burn, so I'm thinking it was the Balph, either that or the falling meteor armor gives a weakness instead of resistance or something... cause I got hit by the behemoth without the armor on and again with the armor on and his burn effect is very short regardless while the Balph is a death sentence unless you find water(which the nether can't have water in it)

**Comment by WTFGeeks** [comment]
Tested meteors fire resistance armour in 0.7.3 working as intended.

**Comment by ArcticHowler** [comment]
loaded up 0.7.3 a while back, had to disable lycanite's mobs again, mainly because the bolph's fire burns indefinitely, can you at least find out how long his attack is meant to burn for? wether or not fire protection gear is worn, no other mob did what he does, nor does any vanilla mob do it, nor lava, nor plain old fire... I don't remember when I turned it off, but since then I've finally been able to go into the nether without dying before I've even had a chance to grab a few nether quartz(I don't really die much at all tbh, kinda dull with just vanilla and a few minor mod mobs, lycanite is good, but just not the balph with it's eternal fire of death...) I had on the tinker's yellow heart container and 2 artifact items a necklace with I think it was 2.5 hearts and that little illuminati symbol looking thing with the same heart bonus and still burned to death, admittedly without wearing fire resistance gear, but those extra heart items actually acted more like they were far better than they listed... and it still burned through them, I love your modpack and would prefer not to have to edit it myself just to play, hell if I had to I'd just disable the bolph myself and keep the rest, but I don't know how to disable particular add-ons nor know what one it's part of, since there's infernal and diablo or whatever they were called, 2 different add-ons that sound like they'd be nether.... figured it wouldn't hurt to ask, I know this was closed by you, but I wanted to ask anyways...
