### ISSUE TITLE
Iron katana & Skilled recipe

### ISSUE THREAD

**Issue by marukusus** [WTFGeeks/Natural-Magic#12]
Just to bring this up the balkons weapon mod iron katana and pam's harvestcraft skilled have the same recipe.

So only way that i was able to solve this to install minetweaker and make separate receipts for them.

I will post my script here if you like to use it.

recipes.remove(harvestcraft:skilletItem);
recipes.addShaped(harvestcraft:skilletItem,[[minecraft:iron_ingot, null, null],
  [null, minecraft:iron_ingot, null],
  [null, null, minecraft:stick]]);

recipes.remove(weaponmod:katana.iron);
recipes.addShaped(weaponmod:katana.iron,[[null, null, minecraft:iron_ingot],
  [null, minecraft:iron_ingot, null],
  [minecraft:stick, null, null]]);

**Comment by WTFGeeks** [comment]
Great thank you very much for helping out, the change will be added in the 6.0.1 update.
