### ISSUE TITLE
Quest book and the other two books went missing when I died in natural magic!!!

### ISSUE THREAD

**Issue by Skywingster** [WTFGeeks/Natural-Magic#120]
Somehow when I died all my stuff were stored in some gravestone and if I break it, it gives me back my stuff but suddenly that thing went missing and all my stuff were gone and I don't care except that the quest book and the two others were gone so pls help me thks. Oh yeah! My username in minecraft is Bryankan8533. Thank you....

**Comment by WTFGeeks** [comment]
This is not a issue, all you need to do is spawn them back in with NEI.

**Comment by Skywingster** [comment]
What is NEI?

**Comment by Skywingster** [comment]
Ohhhh. It is Not Enough Items right?

**Comment by Skywingster** [comment]
But how do I spawn it back

**Comment by Skywingster** [comment]
Do I just spawn it or craft it

**Comment by ArcticHowler** [comment]
Check to see if they have recipes, I assume by 2 other books you mean the tinker's book and the open blocks book... if they do, craft them, if not, in-game type /help and see if you can find a command for them, like /hqm  or anything that might be similar, I'll double check in a bit, but I seem to recall hqm(the quest book's mod) having a command to get the book back.

**Comment by BronyfromOz** [comment]
When you open your inventory NEI displays all items on the right side. On the left side bottom of the screen you can see the options button.  Press that, then select Inventory.  Change Recipe Mode to Cheat Mode (You may need to change the Global setting to allow it). Go back to your inventory, type 'quest' into the search bar and click on the book on the right. Change back to Recipe Mode when you have spawned in your lost items.

Or, you know, craft a book and string together, like NEI tells you to.
