### ISSUE TITLE
Dungeon Like Structure Spawning Inside Village

### ISSUE THREAD

**Issue by ArcticHowler** [WTFGeeks/Natural-Magic#121]
http://steamcommunity.com/sharedfiles/filedetails/?id=357420469

Took that picture using steam for ease of linking to it, but anyways, I found 2 villages on the ground(kinda rare, seems like they spawn more in those endstone towns in the sky than anything these days...) and one of them had this little dungeon place, I can't really consider it a dungeon since all it is, is 2 arrow traps and trip wires everywhere, as well as a double chest, nothing else...

**Comment by WTFGeeks** [comment]
Please remember this is a pace to share bugs and issues, this is neither of those. Please don't do this again.
