### ISSUE TITLE
Botanical Brewery Crafting Issue

### ISSUE THREAD

**Issue by BJConeys** [WTFGeeks/Natural-Magic#123]
I'm trying to craft a Botanical Brewery, but it doesn't seem to be letting me... I've triple checked that I have all the right ingredients, and that they're in the right spot, but it won't let me craft the brewery. Anyone know what's up here? Is this an ID bug?

**Comment by WTFGeeks** [comment]
No it's my fault, I had to change brewery recipes to fix a few issues many updates ago, so any item added that needs one in it's recipe needs to be changed to use the one I added, I'll change the botanical brewery in the next update to use this then you'll be able to craft it, for now just spawn it in as you wont be able to craft it. Expect a update in the next couple of days.
