### ISSUE TITLE
HQM and CHUNKS

### ISSUE THREAD

**Issue by V3ntoRdici** [WTFGeeks/Natural-Magic#124]
I can't claim reward in the Hardcore Questing Book.
And chunks not loading so there are big holes.
Sorry for my english (I'm Italian).
Thanks.

**Comment by ArcticHowler** [comment]
By can't claim reward, do you mean you're getting no items, or is it giving them, but maintaining unclaimed status? The big holes you speak of occur randomly in all versions of vanilla minecraft.
