### ISSUE TITLE
Client/Server Crash

### ISSUE THREAD

**Issue by PedroCaldeira** [WTFGeeks/Natural-Magic#125]
Greetings, so I've been trying out this mod pack in a server I created and I had a problem. When using a Spectral Bolt Scepter from Lycanites Shadow Mobs mod, if I hit a mob with the right click ability the world becomes corrupted, and shuts down the server/same ocurred with the client. 
Thanks.

**Comment by WTFGeeks** [comment]
Hi

I can take a good guess why this is happening, are those scepters supposed to spawn a certain mob when used? I have a feeling as those mobs have been disabled in the pack when you use it and it realises the mob is disabled it breaks itself.

**Comment by PedroCaldeira** [comment]
I don't think it is supposed to spawn a mob. It does create an effect that I haven't seen in any other  scepters from this mod: Fear 

"A dark scepter that fires Spectral Bolts at a rapid rate spreading Shadowfire, with a good chance to Fear a target on a direct hit. Medium Damage, Rapid Fire, Can Cause Fear, Places Shadowfire"

**Comment by WTFGeeks** [comment]
Can you link me the crash/server log please, I'll be able to take a more in-depth look with that cheers.

**Comment by PedroCaldeira** [comment]
How can I get that? (Sorry for the ignorance)

EDIT: I was able to find a crash report, i dont if this is what you need 

---- Minecraft Crash Report ----
// Oops.

Time: 24-12-2014 12:21
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at lycanite.lycanitesmobs.shadowmobs.entity.EntitySpectralbolt.entityLivingCollision(EntitySpectralbolt.java:52)
    at lycanite.lycanitesmobs.api.entity.EntityProjectileBase.func_70184_a(EntityProjectileBase.java:106)
    at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
    at lycanite.lycanitesmobs.api.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:61)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at lycanite.lycanitesmobs.shadowmobs.entity.EntitySpectralbolt.entityLivingCollision(EntitySpectralbolt.java:52)
    at lycanite.lycanitesmobs.api.entity.EntityProjectileBase.func_70184_a(EntityProjectileBase.java:106)
    at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
    at lycanite.lycanitesmobs.api.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:61)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: shadowmobs.spectralbolt (lycanite.lycanitesmobs.shadowmobs.entity.EntitySpectralbolt)
    Entity ID: 384582
    Entity Name: entity.shadowmobs.spectralbolt.name
    Entity's Exact location: 105,30, 65,19, 212,60
    Entity's Block location: World: (105,65,212), Chunk: (at 9,4,4 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: -1,07, -0,54, 0,09
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [EntityPlayerMP['RaisenPT'/14347, l='world', x=142,94, y=67,25, z=209,52]]
    Chunk stats: ServerChunkCache: 495 Drop: 0
    Level seed: -5880880429127186178
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (60,64,240), Chunk: (at 12,4,0 in 3,15; contains blocks 48,0,240 to 63,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 66652 game time, 144313 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 81035 (now: false), thunder time: 67339 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 328890608 bytes (313 MB) / 909639680 bytes (867 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xmx2G -XX:MaxPermSize=256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1272 Minecraft Forge 10.13.2.1272 115 mods loaded, 114 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1272} [Forge Mod Loader](forge-1.7.10-10.13.2.1272-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1272} [Minecraft Forge](forge-1.7.10-10.13.2.1272-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMiner_coremod{0.21.1_build-37} [Core mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.2.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    arsmagica2{1.4.0.005} [Ars Magica 2](1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CrystalWing{1.7.10.r02} [CrystalWing]([1.7.10]CrystalWing-universal-1.7.10.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppleCore{1.0.1} [AppleCore](AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    archmagus{0.6.0} [Archmagus](Archmagus-1.7.10-0.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Artifacts{1.1.0} [Artifacts](Artifacts-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    asielib{0.3.6} [asielib](AsieLib-1.7.10-0.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    attainedDrops{1.3} [Attained Drops](AttainedDrops-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.7} [Waila](Waila-1.5.7a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Automagy{0.17.1} [Automagy](Automagy-1.7.10-0.17.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.11.3.123} [BetterStorage](BetterStorage-1.7.10-0.11.3.123.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.9.1} [BiblioCraft](BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    blocklings{2.1.1} [Blocklings](Blocklings-v2.1.1-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AWWayofTime{v1.3.0} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.0-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{r1.3-146} [Botania](Botania r1.3-146.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    brewingapi{1.2.0} [Brewing-API](Brewing-API-1.7.2-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.3.4} [Carpenter's Blocks](Carpenters Blocks v3.3.4 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.4.14} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.1.320} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.1.3} [Chisel](Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chococraft{4.1.4} [Clienthax's ChocoCraft](ChocoCraft-4.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    colourfulportalsmod{1.4.2} [Colourful Portals](ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.5.25} [EnderStorage](EnderStorage-1.7.10-1.4.5.25-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForbiddenMagic{1.7.10-0.551} [Forbidden Magic](Forbidden Magic-1.7.10-0.551.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{3.3.0.6} [Forestry for Minecraft](forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.1.320} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fossil{1.7.10 Build 7.0.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    foxlib{1.7.10-0.6.0} [FoxLib](FoxLib-1.7.10-0.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ganyssurface{1.9.4} [Gany's Surface](Ganys Surface-1.9.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenCore{1.2.0} [Garden Core](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenContainers{1.2.1} [Garden Containers](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenTrees{1.2.0} [Garden Trees](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraveStone{2.11.1} [GraveStone](GraveStone 2.11.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HardcoreQuesting{The Journey (4.2.1)} [Hardcore Questing Mode](HQM-The Journey %284.2.1%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inpure|core{1.7.10R1.0.0B7} [INpureCore](INpureCore-[1.7.10]1.0.0B7-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    invinciblehamster{1.4} [invinciblehamster](invinciblehamster-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    lycanitesmobs{1.10.6.1 - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    arcticmobs{1.10.6.1 - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    demonmobs{1.10.6.1 - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    desertmobs{1.10.6.1 - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    forestmobs{1.10.6.1 - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    freshwatermobs{1.10.6.1 - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    infernomobs{1.10.6.1 - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    junglemobs{1.10.6.1 - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mountainmobs{1.10.6.1 - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    plainsmobs{1.10.6.1 - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    saltwatermobs{1.10.6.1 - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    shadowmobs{1.10.6.1 - MC 1.7.10} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    swampmobs{1.10.6.1 - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct](TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    meteors{2.14} [Falling Meteors](meteors-1.7.10-2.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mm{1.7.10-1.1} [Minecraft Money](MinecraftMoney-1.7.10-1.2-01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ModTweaker{0.6} [ModTweaker](ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cfm{3.4.6} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.6%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    neiintegration{1.0.3} [NEI Integration](NEIIntegration-MC1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-272.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-517.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    desertcraft{1.7.2b} [Pam's DesertCraft](Pams DesertCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.10d} [Pam's HarvestCraft](Pams HarvestCraft 1.7.10e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectE{Alpha 0.2d-dev11} [ProjectE](ProjectE-Alpha 0.2d-dev11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    xreliquary{1.2} [Reliquary](Reliquary-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Roguelike{1.3.5} [Roguelike Dungeons](roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{14.4} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Sanguimancy{1.1.8} [Sanguimancy](Sanguimancy-1.7.10-1.1.8-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    sinhikabark{1.7.2-0.03} [Sinhika's Bark](SinhikaBark-1.7.2-0.03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SlimeCarnage{1.0.4} [Slime Carnage](SlimeCarnage-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SSR{rc3} [Soul Shards Reborn](SSR-rc3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    statues{2.1.4} [Statues](statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StorageDrawers{1.2.0} [Storage Drawers](StorageDrawers-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    erebus{0.2pre11c} [Erebus](TheErebus-0.2pre11c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    torchLevers{1.4.1} [Torch Levers](TorchLeversV1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMiner{0.21.1} [Vein Miner](VeinMiner-1.7.10_0.21.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMinerModSupport{0.21.1} [Mod Support](VeinMiner-1.7.10_0.21.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VillagersNose{1.3a} [Villager's Nose](VillagersNose-1.7.10-1.3c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    witchery{0.21.0} [Witchery](witchery-1.7.10-0.21.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.1.320} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
    OpenModsLib crash transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:FINISHED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 20; [EntityPlayerMP['RaisenPT'/14347, l='world', x=142,94, y=67,25, z=209,52]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Zarvoxbe** [comment]
Here is my pastebi just in case this bug (append to me this morning) isn't resolved.

http://pastebin.com/uga2WF5j
