### ISSUE TITLE
Uncraftable Brewing Stand

### ISSUE THREAD

**Issue by Muddler-Shanks** [WTFGeeks/Natural-Magic#13]
There are two brewing stand and you need to craft one of them. The only brewing stand you can craft is one from a mod and not the original one. Please help.

**Comment by WTFGeeks** [comment]
This will be fixed in the next version update. This is due to the Brewing API removing the original brewing stand recipe. I have switched all recipes and quests to require the brewing stand from the brewing stand API instead of the vanilla one.
