### ISSUE TITLE
Research Notes Don't Break Down.

### ISSUE THREAD

**Issue by shadow1moon** [WTFGeeks/Natural-Magic#15]
I don't know if this is intential or not, But when you put a Reserch Note in a crafting table, It will not break down. The note i am trying to breakdown also says its an "Unknown Knowlage"

Also if you shift click it gives you an unusable research note.

"After some further experimetnation this bug only happens when shift clicking out of the crafting table, if left clicked and dragged out it works as expected. A bit like the (old?) bug where if you shift click a hardened energy cell out of the table it loses any energy stored as a leadstone energy cell"

**Comment by WTFGeeks** [comment]
I can't seem to reproduce this, can you post some screenshots please.

**Comment by Lexim436** [comment]
i managed to accidentaly reproduce this by making a "reasearch note" in the crafting table using the knowledge fragments to craft it

P.S i haven't asociated my self with thaumcraft stuff before it happened

**Comment by WTFGeeks** [comment]
Alright I'v managed to reproduce it, seems it's a Thaumcraft bug hopefully it'll be fixed in the next thaum content update coming soon.
