### ISSUE TITLE
Worldgen makes aluminum ore very rare

### ISSUE THREAD

**Issue by Phoenixsong** [WTFGeeks/Natural-Magic#17]
Aluminum ore is very rare in comparison to all of the other ores.  Rarer than diamond.  I'm honestly not sure if this is intentional, but if it is, then the "Diggy Diggy" quest should at least require tin instead of aluminum so it can be completed in a reasonable amount of time.

**Comment by WTFGeeks** [comment]
Aluminium has been removed from the quest in the next update. The spawn amounts will resume the same though. Those are the standard Tinkers Construct spawn amounts It just seems rare due to Vanilla ore spawn chance and world height being considerably buffed.
