### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by ArcticHowler** [WTFGeeks/Natural-Magic#177]
I checked WTFG33ks' twitter today(I don't like twitter but it's all he seems to update anymore...) and found out there's a new version for Natural Magic... 0.8, I'd suggest checking the changelog(http://www.atlauncher.com/pack/NaturalMagic) before you update in case there's anything you're against having/losing, you can always do a custom instance with the old version and update certain mods as needed, but if I recall he added some new things himself or was planning to for this version. Personally I'm sad to see HQM go, but what can you do?

**Comment by WTFGeeks** [comment]
Not an issue.
