### ISSUE TITLE
The End Crash

### ISSUE THREAD

**Issue by LurkerintheVoid** [WTFGeeks/Natural-Magic#178]
I updated to 0.8 and trying to enter The End through a portal causes the game to crash now.

**Comment by Ramsteg** [comment]
Hello, my partner and i are having the same issue it seems, We are running 0.8, everything running well, we found the end portal, as i stepped through it, the server crashed, we are playing SMP on LAN, started the game back up, as soon as it was open to LAN, i connected and it crashed again.  This is recreateable atleast on my end

**Comment by WTFGeeks** [comment]
As neither of you have provided a crash log I can only guess this is the same as issue #183 follow the instructions in there. If that is not the issue make sure to always report issues with crash/server logs or I will be unable to help you.
