### ISSUE TITLE
Stacks occasionally don't combine

### ISSUE THREAD

**Issue by Phoenixsong** [WTFGeeks/Natural-Magic#18]
No idea where this is coming from, but I'm occasionally getting stacks of items that won't combine.  NBTExplorer shows that the non-stacking stack has a tag attribute with 0 entries in it.

**Comment by WTFGeeks** [comment]
What items are you having the issue with?

**Comment by Phoenixsong** [comment]
I noticed it on String (vanilla) and Rice (Pam's Harvestcraft).

I have looted a few generated structures, if both of those are found in loot chests then I'm guessing that's the culprit.

**Comment by shadow1moon** [comment]
I have noticed the same thing, except I have the Same item Number EX: Sand 34. I will have 2 sand 34s, one stack with 4 and the other stack with like 32. They wont stack togeather but if i get more it will always go into the larger stack. I will see if i can find a reason for it to do that. But I believe it is normaly with items that you harvest vs items you find in a chest.

**Comment by Phoenixsong** [comment]
@shadow1moon  to clarify: my issue is the same, I've noticed two stacks of String not stacking together and two stacks of Rice not stacking together.

**Comment by MinoForge** [comment]
I've noticed this issue with Smeltery Bricks, after some got picked up out of the middle of the smeltery into the controller. Also Cobblestone, randomly, and a few other things that I didn't write down, because I didn't realize it was a legit bug.

**Comment by xFlameAngel** [comment]
I have this issue with bones, gold, pretty much ANYTHING that has an EMC value, its my belief that the problem may be EE3's calculation is changing the metadata on the items for some unknown reason?

**Comment by ArcticHowler** [comment]
I've had this issue with dirt, I died via a zombie using a bow(doubt it's related) and when I retrieved my stuff from my gravestone, it wouldn't combine with any dirt that I dug up later on, I even lost some of the dirt I had previously, though I noticed if I placed it and then dug it back up, it corrected itself.

**Comment by kiomadoushi** [comment]
I've had the problem with quicksand, raw beef, dirt, sand, (don't know how/why), and VERY frequently with gravel (do know how to reproduce). With the gravel, whenever I get it naturally by placing a torch, it's a different stack from being dug up. If i place the torch variety and dig it up, it stacks with the dug variety.
