### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by IvoryOwl92** [WTFGeeks/Natural-Magic#182]
The game crashes to desktop every time I try to enter a world.
My Java is up-to-date and I made sure to allocate enough RAM for the game to work (2GB).

Here's my pastebin log:
http://pastebin.com/GaSbZwPj

**Comment by ArcticHowler** [comment]
try removing optifine and use fastcraft only...

**Comment by WTFGeeks** [comment]
Looks to me like you have removed chococraft, doing so will effect the dungeon loot in rouge like dungeons basically calling on a item that does not exist, this is just how rouge like handles it's loot tables, you can either play with chococraft or remove rouge like dungeons as well.
