### ISSUE TITLE
Structure Crash

### ISSUE THREAD

**Issue by Time6628** [WTFGeeks/Natural-Magic#183]
A player on my server was adventuring in the end when all of a sudden the server crashed. I checked the console and sure enough it had crashed. 
Log:
http://pastebin.com/d1iv5WZn
Please fix this! :smile: 
Thanks,
-Time

**Comment by WTFGeeks** [comment]
This is an issue with the current version of chocolate quest, I have updated the config folder to fix it for now until the mod itself is fixed, you can either redownload the pack to get the config changes or go into the natural magic config file, locate the chocolate folder then the dungeon config folder in there is caveTests.prop open that and set "chance = 0"
