### ISSUE TITLE
Add FastCraft

### ISSUE THREAD

**Issue by Phoenixsong** [WTFGeeks/Natural-Magic#20]
I am aware that it can't be bundled, however, ATLauncher is designed to make it easy for users to install mods that can't be bundled.  Create a new <mod> XML entry with the url attribute set to "http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820&pageNo=1" and the download attribute set to "browser".  This will cause ATLauncher to tell the user that the mod needs to be downloaded manually, then it will open their browser to the specified URL.  After the user downloads it, they can hit continue, and the launcher will copy it from their downloads folder to the modpack's mods folder.

**Comment by WTFGeeks** [comment]
I'm fully aware of how to write a XML as I did it for this pack. My views on fastcraft were already explained in a previous post.

**Comment by Phoenixsong** [comment]
Sorry, I didn't mean to imply that you didn't know how to write XML.  I would have written out the full XML otherwise.  (Actually, now I realize I should have just made a pull request...)  I just wasn't sure if you were aware of what ATLauncher did when supplied with download="browser".  It basically circumvents "no distribution" rules, since it's exactly what users would be doing otherwise.  (I'm assuming the previous post you're referring to is this: https://github.com/WTFGeeks/Natural-Magic/issues/2)
