### ISSUE TITLE
Watch Of Flowing Time, Emerald seeds grows in seconds

### ISSUE THREAD

**Issue by MasterKatrix** [WTFGeeks/Natural-Magic#211]
watch of flowing time is too owerpowerd, disable in config as default maybe?

**Comment by Armasminecraft** [comment]
People want it in the pack

Sorry!

**Comment by Armasminecraft** [comment]
if you want something op though, talk about EMC

**Comment by MasterKatrix** [comment]
i am disabling it on my own.
