### ISSUE TITLE
Giant Mobs

### ISSUE THREAD

**Issue by NumptyBumpkin** [WTFGeeks/Natural-Magic#22]
Hi i have a couple of giant mobs which seem to be stuck in world, i have a screen grab of one ( a giant tardis) the other is a massive spider. I have no idea how to get rid of them or if anyone else has this issue ? please advise if you can help.
![tardis](https://cloud.githubusercontent.com/assets/8987954/4480377/c6d328ea-4996-11e4-9eb7-c98108033532.jpg)

**Comment by WTFGeeks** [comment]
This is a known issue with Special Mobs I had first hand experience of this from blood n' bones with giant tarantulas. Until Special Mobs fixes this issue, I will remove special mobs spider variants in the next update.
