### ISSUE TITLE
Game will not load.

### ISSUE THREAD

**Issue by mathematiqueNageur** [WTFGeeks/Natural-Magic#24]
Log:
http://paste.atlauncher.com/view/38eeec96

I will be loaded up until the Mojang screen, then it will redirect me to the main launcher window.
Help?

**Comment by WTFGeeks** [comment]
Is this happening when trying to play any other modpacks?

**Comment by mathematiqueNageur** [comment]
When using the AT Launcher, it has not. I have experienced this issue before on Technic Launcher, but it was fixed by increasing the memory requirements or it was fixed by the pack authors in an update.

**Comment by xFlameAngel** [comment]
I had this issue, changed the settings to what i use on the madpack and it fixed it for me, try increasing your permgen to 512 and setting your maxmin to at least 2048
