### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by SilverAndJade** [WTFGeeks/Natural-Magic#25]
Would love to get a server for this up and running, but it keeps crashing.

As far as I can tell from some reading up on the internet, there might be a client-only mod included in the server mod pack? 

I'm admittedly clueless about this though ^_^

Error: Exception in server tick loop
It seems to have something to do with "Torch Leavers" maybe? 
## torchLevers{1.4} [Torch Levers](TorchLeversV1.4.jar) Unloaded

[Server thread/WARN] [FML/torchLevers]: Can't revert to frozen GameData state without freezing first.

**Comment by WTFGeeks** [comment]
Closing this as it's already been explained, please read server files section.

**Comment by Pahiro** [comment]
We're very keen on getting started on this pack. Apologies for the impatience. Do you have any kind of planned release schedule?
