### ISSUE TITLE
weird thing in the water

### ISSUE THREAD

**Issue by carroem9** [WTFGeeks/Natural-Magic#260]
Hello fellow Natural Magic players, 

I have encountered something very strange in my world that I do not know how to deal with. I was walking back towards my base when I was suddenly pulled into the water which was easily 10 blocks away and then killed. I thought at first that I had some how managed to get stuck in a block and suffocated or something. I went back and it did it again. I watched the area from my base the next night and noticed that squids were getting sucked into the area too and killed. Does anyone have any idea what this is? 

Thank you

**Comment by ArcticHowler** [comment]
What you're encountering is a aura node from Thaumcraft, every so often a node will spawn with a certain characteristic that causes it to suck in everything around it, blocks, entities, etc... they can appear anywhere when the world is first generated. 9/10 they appear over oceans, but I've found a few while playing thaumcraft in other packs(that don't use hand built maps) and just by itself on land. Your best bet is to drop all your gear into a chest somewhere safe and destroy the node or mark it on your map as a No Mans Land(so to speak) The radius isn't too extreme but anything on you can get sucked in and destroyed when you die if you're close to it. The node has a special visual around it and you'll notice water source blocks or random blocks in general missing, I would recommend learning more on thaumcraft's wiki, I believe it's called a void node? it's just like any other node in all other aspects.

**Comment by carroem9** [comment]
ArcticHowler, thank you. That is exactly what it is. I shall go educate myself on how to destroy Thaumcraft nodes! :)
