### ISSUE TITLE
Mod suggestions?

### ISSUE THREAD

**Issue by mrdew3** [WTFGeeks/Natural-Magic#28]
On AtLauncher it says to report here for suggestions, so here goes! I think Ars Magica 2 and Hardcore Ender Expansion would be cool to add. Anyway, that's my input. Thanks for all your work, I love the modpack!

**Comment by WTFGeeks** [comment]
Thanks for the suggestions, Ars Magica 2 is already in 6.0.2, shoud be released in a day or two with a few other updates. I won't be adding HEE though, I have other plans for the end in a future update.

**Comment by mrdew3** [comment]
I was looking around and found some mods that you could add, if you think are good, that would use baubles more. Alchemical Bling, Adventurer's Amulets, Baubleicious, and Traveler's Gear.  Necromancy is another cool magic mod. I also found a kinda cool looking mod called The Void. Also, thanks for responding to me. I can't wait to see what you're going to do with the End.
