### ISSUE TITLE
java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Sailren** [WTFGeeks/Natural-Magic#3]
got this little error: http://pastebin.com/DYM5JvXt

**Comment by WTFGeeks** [comment]
Hi Sailren

I can see the mod causing the issue, what exactly were you doing when you got the crash?

**Comment by Sailren** [comment]
i spawned a skeleton spider with an egg, i think this is the name and let her run into house with villagers

**Comment by WTFGeeks** [comment]
Ok cheers, I'll try to replicate this and find a resolve.

**Comment by Sailren** [comment]
these skelli spider hunts for villagers like zombies do
