### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by MimsyMan** [WTFGeeks/Natural-Magic#31]
I read through the posts here and was wondering,  do you have any idea when the server-friendly version will be doable? I'm really looking forward to playing this pack with my pals, it looks really fun, but a few of us just aren't singleplayer-savvy anymore with Minecraft :P

**Comment by Skyllian** [comment]
the question you can find in #6

**Comment by MimsyMan** [comment]
Oh okay, thanks
