### ISSUE TITLE
(Reliquary) Ghost items when filling Empty Vials

### ISSUE THREAD

**Issue by MinoForge** [WTFGeeks/Natural-Magic#33]
If I have a stack(16) of empty vials from Reliquary, and just hold right-click on some water to fill them up, while I have a full inventory, they spit out on the ground as I fill them(yay). When I go to pick them up, I pick up some of the floating items(I get 16, so nothing is 'lost'), but there are still floating items. Appears that a relog makes them go away. Dunno if this is the modpack, or the mod, but I figured I'd report it.

**Comment by WTFGeeks** [comment]
Thanks for letting me know, this is a bug on reliquarys end as far as I'm aware it's a fairly easy fix, I take it you're using v0.6.2 of the pack if so that version of reliquary is getting a update in the next few days. that should fix it.

**Comment by MinoForge** [comment]
Yeah, 0.6.2
Should have specified that. Still new at reporting bugs.
