### ISSUE TITLE
New Worlds crashes game/gets deleted

### ISSUE THREAD

**Issue by jp-c0de** [WTFGeeks/Natural-Magic#37]
Today I logged in to find my world was no longer there. So I created a new world and it crashes the game. If I go back on that world will no longer be there either. I even reinstalled the pack and it still won't work. Guessing its a bug with one of the mods or something.

**Comment by WTFGeeks** [comment]
Please post a crash report, so I can see what's going on.

**Comment by jp-c0de** [comment]
How do I do that? I have the crash report but I can't paste it here.

**Comment by jp-c0de** [comment]
Here is the crash report
https://www.dropbox.com/s/8m55d90tv836wrx/crash-2014-10-16_19.22.46-server.txt?dl=0

**Comment by jp-c0de** [comment]
It seems like it is working fine now, I'm not sure why it didn't work before but it's all good now.
