### ISSUE TITLE
Vacuum Hopper cant set sides

### ISSUE THREAD

**Issue by xFlameAngel** [WTFGeeks/Natural-Magic#39]
For some unknown reason, whilst trying to abuse the magical crops mod, i'm using a setup using the Gany's Surface Farm Manager (note i did try this with a chest and a transfer node and it appeared to work just FINE inserting items into the farm manager) but i cant set ANY of the sides on the vacuum hopper, at one point i managed to set a side on the Vacuum hopper, unfortunately i was just madly clicking on it by this point and managed to set the xp instead of the items output (in the wrong direction mind you!) Please dont make me use golems for this those derpy little bastards drive me nuts!

**Comment by WTFGeeks** [comment]
I'm currently testing Natural Magic v0.6.3 before release and there has been a open blocks update. I'v had a play around with the vacuum hopper and it does seem it takes a couple of clicks for it to set a side, but I'm not unable to do so. This could have been resolved in the newest update I'm currently testing. Once 0.6.3 is released on the atlauncher I'll wait to see if this has been resolved.

**Comment by postal291** [comment]
Worked no problem, had to double click.
