### ISSUE TITLE
Crash on Server Start

### ISSUE THREAD

**Issue by zastil** [WTFGeeks/Natural-Magic#4]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 19-9-14 19:59
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Lnet/minecraft/client/resources/data/IMetadataSerializer;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Unknown Source)
    at java.lang.Class.getDeclaredField(Unknown Source)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:313)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.data.IMetadataSerializer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 31 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 540670592 bytes (515 MB) / 878182400 bytes (837 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xmx2G -XX:MaxPermSize=256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 117 mods loaded, 116 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.25.1208} [Forge Mod Loader](forge-1.7.10-10.13.0.1208-universal.jar) Unloaded->Constructed
    Forge{10.13.0.1208} [Minecraft Forge](forge-1.7.10-10.13.0.1208-universal.jar) Unloaded->Constructed
    CodeChickenCore{1.0.3.25} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.3.51} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.51-universal.jar) Unloaded->Constructed
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed
    lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed
    bspkrsCore{6.14} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed
    ArmorStatusHUD{1.27} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.27.jar) Unloaded->Constructed
    CrystalWing{1.7.10.r01} [CrystalWing]([1.7.10]CrystalWing-universal-1.7.10.r01.jar) Unloaded->Constructed
    StatusEffectHUD{1.26} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.26.jar) Unloaded->Constructed
    Treecapitator{1.7.2} [Treecapitator]([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed
    archmagus{0.6.0} [Archmagus](Archmagus-1.7.10-0.6.0.jar) Unloaded->Constructed
    asielib{0.2.11} [asielib](AsieLib-1.7.10-0.2.12.jar) Unloaded->Constructed
    Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded->Constructed
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed
    BackTools{4.0.0} [BackTools](BackTools-4.0.0.jar) Unloaded->Constructed
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed
    betterstorage{0.10.0.112-dev} [BetterStorage](BetterStorage-1.7.10-0.10.1.113.jar) Unloaded->Constructed
    BiblioCraft{1.8.1} [BiblioCraft](BiblioCraft[v1.8.1][MC1.7.10].jar) Unloaded->Constructed
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.991-universal.jar) Unloaded->Constructed
    BiblioWoodsBoP{1.7} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.7].jar) Unloaded->Constructed
    Forestry{3.0.0.136} [Forestry for Minecraft](forestry_1.7.10-3.0.0.136.jar) Unloaded->Constructed
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed
    BinnieCore{2.0-dev4} [Binnie Core](binnie-mods-2.0-dev4.jar) Unloaded->Constructed
    Botany{2.0-dev4} [Botany](binnie-mods-2.0-dev4.jar) Unloaded->Constructed
    ExtraBees{2.0-dev4} [Extra Bees](binnie-mods-2.0-dev4.jar) Unloaded->Constructed
    ExtraTrees{2.0-dev4} [Extra Trees](binnie-mods-2.0-dev4.jar) Unloaded->Constructed
    Genetics{2.0-dev4} [Genetics](binnie-mods-2.0-dev4.jar) Unloaded->Constructed
    blocklings{1.2.0} [Blocklings](Blocklings-v1.2.0-MC1.7.10.jar) Unloaded->Constructed
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.1.0%281.7.10%29.jar) Unloaded->Constructed
    Botania{r1.2-116} [Botania](Botania r1.2-116.jar) Unloaded->Constructed
    brewingapi{1.2.0} [Brewing-API](Brewing-API-1.7.2-1.2.0.jar) Unloaded->Constructed
    CarpentersBlocks{3.2.8} [Carpenter's Blocks](Carpenters Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed
    colourfulportalsmod{1.4.2} [Colourful Portals](ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed
    CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) Unloaded->Constructed
    menagerie{1.0} [menagerie](dark_menagerie-1.7.10-beta-1.0.jar) Unloaded->Constructed
    DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) Unloaded->Constructed
    DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) Unloaded->Constructed
    EnderStorage{1.4.5.22} [EnderStorage](EnderStorage-1.7.10-1.4.5.22-universal.jar) Unloaded->Constructed
    ForgeMultipart{1.1.0.300} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed
    ftea{1.4b} [Flower Tea](Flower Tea v1.4b [1.7.10].jar) Unloaded->Constructed
    Waila{1.5.4a} [Waila](Waila-1.5.4a_1.7.10.jar) Unloaded->Constructed
    ThaumicTinkerer{2.5-1.7.10-158} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-158.jar) Unloaded->Constructed
    ForbiddenMagic{1.7.10-0.52} [Forbidden Magic](Forbidden Magic-1.7.10-0.52.jar) Unloaded->Constructed
    McMultipart{1.1.0.300} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed
    fossil{1.7.10 Build 6.4b} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-6.4b.jar) Unloaded->Constructed
    foxlib{0.4.0} [FoxLib](FoxLib-1.7.10-0.4.1.jar) Unloaded->Constructed
    ganyssurface{1.9.1} [Gany's Surface](Ganys Surface-1.9.1.jar) Unloaded->Constructed
    GardenCore{1.2.0} [Garden Core](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed
    GardenContainers{1.2.1} [Garden Containers](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed
    GardenTrees{1.2.0} [Garden Trees](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed
    cgo{3.0.8} [CG Origin](GGOrigin-1.7.10-3.0.8.jar) Unloaded->Constructed
    GraveStone{2.9.4} [GraveStone](GraveStone 2.9.4.jar) Unloaded->Constructed
    Hats{4.0.0} [Hats](Hats-4.0.0.jar) Unloaded->Constructed
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded->Constructed
    HardcoreQuesting{The Journey (4.2.1)} [Hardcore Questing Mode](HQM-The Journey %284.2.1%29.jar) Unloaded->Constructed
    inpure|core{1.7.10R1.0.0B1} [INpureCore](INpureCore-[1.7.10]1.0.0B1-1.jar) Unloaded->Constructed
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed
    invinciblehamster{1.4} [invinciblehamster](invinciblehamster-1.0.0.jar) Unloaded->Constructed
    LoreExp{1.0.0} [Lore Expansion](LoreExpansion-1.7.X-1.0.0.22-universal.jar) Unloaded->Constructed
    LostBooks{1.2.1} [Lost Books](LostBooks-1.7.10-1.2.1.jar) Unloaded->Constructed
    LunatriusCore{1.1.2.11} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.11-universal.jar) Unloaded->Constructed
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed
    meteors{2.13.1} [Falling Meteors](meteors-1.7.10-2.13.1.jar) Unloaded->Constructed
    MineMenu{1.1.0} [MineMenu](MineMenu-1.7.2-1.1.0.20-universal.jar) Unloaded->Constructed
    MobAmputation{4.0.0} [MobAmputation](MobAmputation-4.0.0.jar) Unloaded->Constructed
    MobDismemberment{4.0.0} [MobDismemberment](MobDismemberment-4.0.0.jar) Unloaded->Constructed
    cfm{3.3.5} [ß6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.3.5%281.7.10%29.jar) Unloaded->Constructed
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIPlugins{1.1.0.8-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.8-unofficial.jar) Unloaded->Constructed
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-432.jar) Unloaded->Constructed
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed
    desertcraft{1.7.2b} [Pam's DesertCraft](Pams DesertCraft 1.7.10a.zip) Unloaded->Constructed
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pams HarvestCraft 1.7.10b.jar) Unloaded->Constructed
    ProjectZulu|Core{1.7.10.1.3a} [Project Zulu 1.7.10](ProjectZulu-1.7.10-1.3a.jar) Unloaded->Constructed
    ReCubed{1.1.1} [ReCubed](ReCubed 1.1.1.jar) Unloaded->Constructed
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed
    xreliquary{1.2.DEV} [Reliquary](Reliquary-1.2.137.jar) Unloaded->Constructed
    Roguelike{1.3.5} [Roguelike Dungeons](roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed
    AS_Ruins{13.8} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed
    Sanguimancy{1.0.0} [Sanguimancy](Sanguimancy-1.7.10-1.0.0.jar) Unloaded->Constructed
    Schematica{1.7.2.96} [Schematica](Schematica-1.7.10-1.7.2.96-universal.jar) Unloaded->Constructed
    shadowworld{1.3.0} [Shadow World](shadowworld-1.3.0.jar) Unloaded->Constructed
    sinhikabark{1.7.2-0.03} [Sinhika's Bark](SinhikaBark-1.7.2-0.03.jar) Unloaded->Constructed
    SlimeCarnage{Release} [Slime Carnage](SlimeCarnage-1.0.2.jar) Unloaded->Constructed
    SpecialMobs{3.0.2} [Special Mobs](SpecialMobs-1.7.10-3.0.2.jar) Unloaded->Constructed
    SSR{Alpha 0.9a} [Soul Shards: Reborn](SSR_Alpha0.9c.jar) Unloaded->Constructed
    statues{2.1.3} [Statues](statues-1.7.10-2.1.3.jar) Unloaded->Constructed
    StorageDrawers{1.1.1} [Storage Drawers](StorageDrawers-1.1.1.jar) Unloaded->Constructed
    Tails{$version} [Tails](Tails-1.7.10-1.0.1.jar) Unloaded->Constructed
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed
    torchLevers{1.4} [Torch Levers](TorchLeversV1.4.jar) Unloaded
    TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) Unloaded
    TwilightForest{2.2.3} [The Twilight Forest](twilightforest-1.7.2-2.2.3.jar) Unloaded
    VillagersNose{1.3a} [Villager's Nose](VillagersNose-1.7.10-1.3a.jar) Unloaded
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2.jar) Unloaded
    weepingangels{3.0.2} [Weeping Angels](WeepingAngels-1.7.10-3.0.2.jar) Unloaded
    wtp{1.0} [WTP](whatsthispack-1.7.2-1.0.jar) Unloaded
    witchery{0.20.5} [Witchery](witchery-1.7.10-0.20.5.jar) Unloaded
    ForgeMicroblock{1.1.0.300} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by WTFGeeks** [comment]
Sorry as it says on the Natural Magic page, server files will be coming out in the next update. This version does not support them.
