### ISSUE TITLE
HQM Dwarven Tinkers: Cheap and Cheerful Quest

### ISSUE THREAD

**Issue by seiryen** [WTFGeeks/Natural-Magic#40]
The quest requires that you craft the version of wooden armor from Tinker's Construct to compleyte the quest but when you actually craft the armor you get the set from Gany's Surface instead and so the HQM doesn't count it as a completion.

**Comment by WTFGeeks** [comment]
This will be resolved in v0.6.3 expect a release within the next couple of days.
