### ISSUE TITLE
Magnetization issue

### ISSUE THREAD

**Issue by xFlameAngel** [WTFGeeks/Natural-Magic#41]
The Falling meteors magnetization enchants now come witha  lovely magnetization controller, unfortunately it doesnt work for everyone, for example one of my computers the keybind works fine, the other does not, and even when i did manage to turn magnet off on one of my computers, It still appears to be happy sucking up items and causing visual glitches making you unable to loot items

**Comment by WTFGeeks** [comment]
Tested in 0.7.3 working as intended.
