### ISSUE TITLE
Keep crashing, currently stuck next to the source

### ISSUE THREAD

**Issue by ArcticHowler** [WTFGeeks/Natural-Magic#45]
I came across a partially buried structure in the desert biome made of cobblestone, uncertain if it's a mod dungeon or what exactly it might be, but upon getting close I crashed, I attempted to get close again, crashed again... Now I'm stuck in an infinite loop of crashing in this world.

**Comment by xFlameAngel** [comment]
We appear to be suffering from the same issue, i found a half buried cobble structure, got close and corrupted, cant even move player via .dat files i've found it all appears to have just.... broken.

**Comment by xFlameAngel** [comment]
Well since we have this thread open, we might as well put up some pastebin crash reports while were here so he knows whats going on!
http://pastebin.com/SurbuUpZ

**Comment by ArcticHowler** [comment]
Crashlog: http://pastebin.com/Kk9wDf2K

RuinsPositionsFile: http://pastebin.com/84PAYP3y

Both set to expire in 1 week to avoid cluttering their site... I figure he can use the RuinsPositionsFile to id what the source might be, I'm roughly 3 blocks away from it, though I can't really decide what it might be, I know that the Ocean is near this little stretch of Desert(and I know it's a Desert or at least a sub-Biome of a Desert biome due to the Desert Nova and Quicksand everywhere, the desert seems to be on the edge of a Beach though...Might be one of those shipwrecks buried underground, uncertain...). I will say that the only ruins that share the X axis,  with my location is the spawn point and few share any others, I don't know the exact size of the structure that is suspect, nor what size of a zone it would "protect".

**Comment by xFlameAngel** [comment]
I also appear to be in a desert Biome Howler, could you help me parse my ruins with yours to try and find any similarities? I have render distance set to 12 chunks so anything within.... I think about 150 blocks is fair game?

http://pastebin.com/y0Wmpj9q

**Comment by ArcticHowler** [comment]
Thing is, the RuinsPositionsFile is to prevent other ruins from spawning in that area using the listing of xmin ymin zmin xmax ymax zmax, I'm no expert on it, but from my understanding the structures center in those zones and no other ruin/structure is supposed to spawn within the radius to prevent having multiple structures fusing... It very well could be something else in the region and it just happens to be attached to the ruins in some way, personally I'm not a fan of copy and pasting stuff all the time, case in point using something like that Voxelarrow or w.e it was called, the mod that lets you basically cut into the world as you see fit, corrupts chunks like mad and can end up crashing anyone who goes near them, in some cases even crashing them if they connect to the server at all, whether they're in that corrupted chunk or not... as for your file, I'm not experienced enough to properly suggest which ones are doing it... We'll just have to wait and see what the maker thinks @.@

**Comment by WTFGeeks** [comment]
This is resolved in v0.7 some massive changes, make sure to check the changelog.
