### ISSUE TITLE
questbook lore glitch

### ISSUE THREAD

**Issue by lewisnova** [WTFGeeks/Natural-Magic#46]
when i have done the first quest and handed it in i only get the cookie and tea but no lore page, also the quest book still thinks its uncompleted

**Comment by WTFGeeks** [comment]
Are you checking the lore book? pages don't get given to the player but are instantly placed in the book, to open the book press L.  Uncompleted quests showing is a known HQM issue already being monitored #1

**Comment by lewisnova** [comment]
yeah i got that the secound time trying it, i was expecting it to go in my inventory
