### ISSUE TITLE
Crash when crafting Shadow Wood planks.

### ISSUE THREAD

**Issue by Lexim436** [WTFGeeks/Natural-Magic#5]
My game crashed at the Shadow World, world gen option

error string: I don't know will have to dig deep later and edit this
steps to error:
I loaded in a new world with the terrain gen set to "Shadow world" with cheat mode on and bonus chest.
I proceeded to mine a shadow log and when i shift clicked it to turn it into shadow planks (i think were the name) crashed my game.

**Comment by WTFGeeks** [comment]
Thanks for the report I will test this and contact the author if required.

**Comment by WTFGeeks** [comment]
As quoted via the author "Put your diary in a chest and try it again. This bug will be fixed in the next version." seems this is a known issue and will be resolved shortly.

**Comment by WTFGeeks** [comment]
This has now been fixed via the mod author, will be resolved in the next Natural Magic update.
