### ISSUE TITLE
Can't Create/Place Spell Recipe's on Lectern Ars Magica 2

### ISSUE THREAD

**Issue by JonathanRiche** [WTFGeeks/Natural-Magic#51]
After creating spell recipe's and trying to right click to place them on the lectern, recipe's do not get placed and in turn not able to make spells without doing it in creative mode(clicking make spell in inscription table).

**Comment by ArcticHowler** [comment]
I had this issue myself a few times, uncertain how I managed it, but I managed it outside of creative once...

**Comment by LeeLR** [comment]
you have to sign the book and close the book then you can place it on the lecturn
