### ISSUE TITLE
Servers and stuff

### ISSUE THREAD

**Issue by FreezyT** [WTFGeeks/Natural-Magic#53]
i've been trying to create a server and i don't know the problem is, but every time i start the "LaunchServer" it just says this

"[08:06:02] [Server thread/ERROR]: This crash report has been saved to: D:\ATLaun
cher\Servers\NaturalMagic_063.\crash-reports\crash-2014-11-01_08.06.02-server.txt
[08:06:02] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[08:06:02] [Server thread/INFO] [FML]: Applying holder lookups
[08:06:02] [Server thread/INFO] [FML]: Holder lookups applied
[08:06:02] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded."

I know that there are some client sided mods, and i don't know all of them. i don't know which i should delete and which i should keep. but can someone help me with creating a server, please.

**Comment by ArcticHowler** [comment]
He doesn't have it configured for server use yet, currently doing bug hunt before that is implemented...

**Comment by FreezyT** [comment]
oh okey ^^ thank you

**Comment by WTFGeeks** [comment]
If you download the server via that atlauncher I have it configured in v0.7 that no work on your part is needed, simply download it launch the server.bat make sure the eula is accepted and it will work. I have tested this numerous times with v0.7 and had no problem.  Obviously you need to make sure the mods on the client and server are the same except for that no messing about with the mods is needed.
