### ISSUE TITLE
Open Blocks gravestones don't hold everything

### ISSUE THREAD

**Issue by BronyfromOz** [WTFGeeks/Natural-Magic#55]
I failed at retreating from fire slimes (I hate them so much) and when I opened my grave all that came out was my Traveller's Glove and Knapsack.
All armor (just a traveller's set) and baubles was lost, as well as everything in my inventory.
Knapsack was empty at the time so I'm not sure if items stored there would've been saved.
EDIT- Knapsack stuff does get stored in grave.

**Comment by kiomadoushi** [comment]
If by fire slime you mean the vanilla magma cube often called "fire slime", then I feel this might be better brought to the attention of Open Blocks themselves:
https://github.com/OpenMods/OpenBlocks/issues

If you mean the slime carnage fiery slime, slightly different name, then I can only recommend soulbinding equipment in the meantime. Level 1 enchanting should be able to get you a soulbinding book, then you can enchant to get a soulbound container you never drop on death, so can't lose. The silky backpacks that require bees are enchantable. That should at least keep you from losing more items.

**Comment by BronyfromOz** [comment]
not Magma Cubes, definitly Fire Slimes from carnage.  But yeah I'll go tell OpenBlocks about the issue

**Comment by WTFGeeks** [comment]
I have disabled openblocks graves in v0.7 weirdly In all my testing it's always been gravestones mod grave that generated after death never one from openblocks, but just to be sure they are disabled in v0.7 I tested the items you said you lost and they were all saved inside the gravestones grave.
