### ISSUE TITLE
Inventory memory loss or NEI lag/ memory loss

### ISSUE THREAD

**Issue by SamuelX16** [WTFGeeks/Natural-Magic#56]
I just started play natural Magic Beta 6.3 this week. After playing it for a few days when I go into my inventory my cursor would move very slowly and I could not search for anything in NEI. After pressing F3 I saw that memory was going back and forth from 1000 to nearly 2000 megabytes rapidly. This also seemed to of happened after I was looking in my guest book try to receive a reward I already claimed already but is still showing up as unclaimed reward.

**Comment by BronyfromOz** [comment]
I'm also suffering from NEI slowdown after just hours.

**Comment by WTFGeeks** [comment]
This should all be resolved in v0.7
