### ISSUE TITLE
Claiming rewards causing infinite crash

### ISSUE THREAD

**Issue by ToTheMaxHD** [WTFGeeks/Natural-Magic#61]
I am playing on a server with my friend and when I tried to claim my reward for the first quest in the book, It kicked me saying "Internal server error". I tried to relog and now whenever I join it instantly kicks me saying it was forcibly closed by a remote host when in reality the server is still running fine

**Comment by ArcticHowler** [comment]
Read previous issues and/or closed ones...

**Comment by ToTheMaxHD** [comment]
Okay, thanks. Any idea on when 0.7 will be out?

**Comment by ArcticHowler** [comment]
not a clue, depends on how long it takes for him to crush all the bugs...
