### ISSUE TITLE
Consecrated soil unfinishable

### ISSUE THREAD

**Issue by Dalhai** [WTFGeeks/Natural-Magic#62]
The quests "Strange new world / Cleansing the lands" and "Dwarfen tinkerer / Consecrated soil" can not be finished.
- <s>**Cleansing the lands**
  The creeper kill count does not seem to increase (no creeper type seems to be working). </s>
- **Consecrated soil** 
  The consecrated soil is not detected after smelting the graveyard soil in a vanilla furnace.

I am not talking about the current HQM bug with unclaimed rewards. The requirements for the quests can not be met at all.

**Comment by ArcticHowler** [comment]
Are you using those monster dismemberment mods? I've noticed that they don't work for a lot of things in general, perhaps remove them if you're using them?

**Comment by Dalhai** [comment]
This seems to fix the issue with **Cleansing the lands**. 

The consecrated soil issue remains. Though I'm not sure this is a bug you guys can fix.

**Comment by ArcticHowler** [comment]
come to think of it... for the consecrated soil... have you tried making the full stack? some of the quests don't recognize it until the stack is finished, while others will count each item individually... I haven't gotten that far into the quest book, too many issues in other things, but if it has manual detect button, should be able to do that when you have enough

**Comment by Dalhai** [comment]
The quest requires me to craft 15 consecrated soil. I crafted all of them, just to make sure. Still does not work. If you mean an actual stack, as in 64 consecrated soil, no, I have not tried that yet.

There is also a problem with the slimy grass. When you harvest the slime grass blocks, they get a different damage value (I think it was 1928:4, while 1928 was required). Spawning them in via creative mode completed the task.

**Comment by WTFGeeks** [comment]
This should be fixed in v0.7 tested it earlier worked fine.
