### ISSUE TITLE
Botania Mana Crafting not working

### ISSUE THREAD

**Issue by Leekit** [WTFGeeks/Natural-Magic#63]
Whenever I drop items onto the mana pool it doesn't create the items it says it can create.

For instance I tried to make pasture seeds with tall grass and it didn't work. Same issue with Mana Pearls.

**Comment by WTFGeeks** [comment]
Are you using the correct mana pool? there is a nei derp in botania that shows you can use a diluted mana pool for some recipes when this is not the case.

**Comment by WTFGeeks** [comment]
Tested in v0.7 working fine.
