### ISSUE TITLE
Changelogs?

### ISSUE THREAD

**Issue by Lankoran** [WTFGeeks/Natural-Magic#65]
Does anyone know if there are changelogs available for Natural Magic, we've recently had update 0.7 for beta, but i can't find a changelog for whats gone on with the pack. I'm running a private server with my partner and would appreciate being able to get a headsup on the changes before we decide to put them live. 

Thanks in advance for any replies

**Comment by WTFGeeks** [comment]
All changelogs can be found here http://www.atlauncher.com/pack/NaturalMagic
