### ISSUE TITLE
0.7.1 Generation changes

### ISSUE THREAD

**Issue by Lankoran** [WTFGeeks/Natural-Magic#68]
The changes to various dungeon and ruin generation changes are listed in the changelog for 0.7.1, but theres no clarification on wether the values have been increased, or decreased, is it possible to get some information on this? I'm about to generate a new world for my server (Currently running on 0.7.0) and would like to know if i should hold out for my server host to provide a working 0.7.1 for a better generated world?

**Comment by WTFGeeks** [comment]
Nothing was changed with ruins, doom like and better dungeons generation was decreased so they are better spaced out, to reduce lag as they are very large dungeons so lots of entities spawners, chests etc.
