### ISSUE TITLE
Vein Miner  (Quick help)

### ISSUE THREAD

**Issue by ToTheMaxHD** [WTFGeeks/Natural-Magic#70]
Hi, just wondering how to use vein miner properly. I have set it to sneak but it doesn't seem to be working, and no there aren't any overlapping controls. Even when I had it set to GRAVE, the default thing, it still wasn't working. All you do is hold down shift and punch an item right?

**Comment by FeistyPancake** [comment]
You know that you have to use the appropriate tool for the thing you want to mine? Example: Axe for trees, Pick for stone.

**Comment by ToTheMaxHD** [comment]
Yeah, I figured it out. I played Mad Pack 2 where it was way more OP and you could vein mine with a fist. All good now, thanks
