### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by FeistyPancake** [WTFGeeks/Natural-Magic#71]
Started playing the new updated lately. What mod causes all the crazy weather conditions? Looks like a cool mod I might include in my pack! Love playing this pack and hope you have fun with it :)

**Comment by ToTheMaxHD** [comment]
I'm assuming you are talking about the events that pop up on your screen? Like "Bam Storm" or Winged Venom" and that is part of Lycanites mobs

**Comment by FeistyPancake** [comment]
Yea, thanks. Thought about adding it, but since all those mobs would be hard to balance with everything, I decided to leave it out.
