### ISSUE TITLE
Liquid Automation

### ISSUE THREAD

**Issue by BleakStasis** [WTFGeeks/Natural-Magic#73]
Looking through all the mods there doesn't seem to be any way to move liquids around. The transfer nodes from ExtraUtilities is disabled too, is this intended? If so, is there a way to move liquids (like from Forestry) that I'm missing?

**Comment by WTFGeeks** [comment]
Open blocks tank is probably the easiest way, if it was me though I'd make a rod of the seas from Botania, then you can spawn water source blocks whenever you like at the cost of a bit of mana.

**Comment by BleakStasis** [comment]
Thanks for the quick response. The tanks are definitely good for carrying liquids around. I was trying to say automating liquid transfer like biomass from the fermenter to the still or even to the tank. The fermenter doesn't output liquid on its own.
