### ISSUE TITLE
Vespids and their nests spawns

### ISSUE THREAD

**Issue by Lankoran** [WTFGeeks/Natural-Magic#75]
I know you've already had issues with the lycanites stuff, but i noticed a bit of a problem with these things, our version of Lycanites doesn't have the disolving hives, which means that these humongous hives don't seem to be despawning, I've personally gone and edited their spawn rate as part of the "events" though, just because living in a forest otherwise is nearly impossible :P

**Comment by ArcticHowler** [comment]
I love those hives, beautiful things, just wish there wasn't 20 of them in the same chunk after that Swarm event... luckily if you kill the queen the construction stops...

**Comment by Lankoran** [comment]
The construction stops yeah, but the hive never goes away :S in the next update after the version installed in this pack the hive deteriorates (Like leaves) after the queen dies, returning the world to normal

**Comment by WTFGeeks** [comment]
I have changed the config to disable queens building hives for the time being, you can either re install the pack to get the config changes or go into the lycanites config folder and under junglemobs-general set "Vespid Hive Building"=false
