### ISSUE TITLE
CTD While opening Inventories

### ISSUE THREAD

**Issue by Lankoran** [WTFGeeks/Natural-Magic#76]
Occasionally i get random CTD's while opening various inventories, there are two in particular it happens with frequently, i'm not sure if this is a client issue and requires a re-install, or a Server issue though, was hoping i might get some clarification on that here. 

Sometimes when opening the creative inventory (Standard inventory in Creative mode, when trying to change tabs, i crash to desktop) and other times when trying to open the Chocobo Saddlebags inventory i crash, I'm assuming that this crash isn't a result of a client issue because if i use the chocodex to remove the saddlebags, then re-apply them i can open the inventory again. Not sure of the cause but would appreciate any help you could spare.

**Comment by WTFGeeks** [comment]
Please can you send me the crash reports.

**Comment by Lankoran** [comment]
I've got a couple of crash reports from this today, i'm not sure what the best medium to upload them is though, there doesn't seem to be an attachment option for text files

**Comment by WTFGeeks** [comment]
copy them to pastebin.com and send me the links cheers.

**Comment by Lankoran** [comment]
Heres the most recent one : 

http://pastebin.com/UR91WGBe

**Comment by WTFGeeks** [comment]
Those last 2 reports are identical to the first, only send reports if they are different thanks.

**Comment by Lankoran** [comment]
Ah Sorry, I didn't actually read them as i don't have any aptitude in that department.

**Comment by WTFGeeks** [comment]
The issue was coming from Sanguimancy, in it's latest version this seems to be resolved, will be updated in v0.7.2 coming out soon.
