### ISSUE TITLE
Just suggestions

### ISSUE THREAD

**Issue by BronyfromOz** [WTFGeeks/Natural-Magic#77]
First off I want to say I LOVE your pack.  It's the only way I play MC anymore and I'm seriously considering bankrolling a server.
Vanilla worlds are annoyingly random, instead of BoP (which can be overwhelming) perhaps Alternate Terrain Generation would be good to add.
The Lycanites mobs are poorly designed, textured and balanced (being attacked on Peaceful is just stupid). I would not mind if they were removed.
That's all I got for you so far, I'll let you know if I have any more.

Keep up the fantastic work.

**Comment by WTFGeeks** [comment]
Thanks for the suggestions.
