### ISSUE TITLE
Fiery Slime burns all in Nether....

### ISSUE THREAD

**Issue by poul54** [WTFGeeks/Natural-Magic#79]
Hello.

 Vs. 0.7.1, 0.7.0, 0.6.3

Is very Difficult stay in Nether.

 Fiery Slimes burns all ... looks like a true Inferno.

**Comment by WTFGeeks** [comment]
This has now been fixed quartz will now spawn in newly generated chunks, seems it was a issue with CoFHCore, this does not need a update as it's a hot fix but to get the config changes re-installing the pack will be required, give it 15 minutes though as I'v only just resubmitted them. For the fire slimes I have reduced the spawn quantity.
