### ISSUE TITLE
Block breaking lag

### ISSUE THREAD

**Issue by mysticmay0** [WTFGeeks/Natural-Magic#80]
Whenever i host any version of the natural magic server my friends who try to connect to  server experience block breaking, and interface lag. I however do not experience either of those as the host. I don't know what to do and we all really want to play this modpack, so help would really be appreciated.

**Comment by WTFGeeks** [comment]
This sounds very much a host issue, I'v set up multiple servers and not hand this issue with anyone logging in as long as they are within the same region, it's to be expected that of the host is in the UK and those logging in are in america client to server lag will happen. feel free to send me your server logs though and I'll have a look through though just in case something is not set up correctly.
