### ISSUE TITLE
Ganys Surface Blocks disabled?

### ISSUE THREAD

**Issue by Lankoran** [WTFGeeks/Natural-Magic#81]
Playing through the game i recently wondered why i'd not found any granite, or diorite or any of the other stones added by Ganys, so i went to check the configs and they've been disabled? there any reason behind this i.e. generation problems or is it just personal preference for the pack? 

Basically curious if its safe to re-enable them.

**Comment by WTFGeeks** [comment]
feel free to re enable them, the only reason I disabled them was due to small amounts of lag in generation any decent computer system would not feel this but for those with dated machines it may become slightly annoying, that is why they were disabled as I have to consider all users,
