### ISSUE TITLE
A suggestion, a spelling problem, and progression problems

### ISSUE THREAD

**Issue by efeuds** [WTFGeeks/Natural-Magic#82]
First suggestion: Automagy, a thaumcraft add on that allows for some really cool magical redstone automation stuff.
Second Spelling: In the quest book the word mite is used a lot when it should be might. A mite is a insect/something that is tiny (i.e. a termite, dustmite etc.). Might is either a synonym for strength/power (i.e. he lifted with all his might) or the past tense of may which is what you want. 
This happens in the Monster Hunter quest "these monsters mite seem scary". This should be "these monsters might seem scary". 
The same issue happens in Cheap and Cheerful under Dwarven Tinkers. 
Finally Progression: In the Strange New World Quest line there are issues with the food branch. The Feeling Peckish Quest requires you to make a backpack with leather, before you do the quest which requires you to get the supplies for an animal farm (fences gates and leads) where you would actually get leather from said farm. 
Second problem is with the Dwarven Tinkers quest line. The first quest requires you to make all the materials for a tinkers construct wooden pickaxe, even though you should at least have stone tools by this point from the Strange New World quest line. This also goes for the quest which requires you to make wood armor, which you should also already have.

**Comment by WTFGeeks** [comment]
Thanks for the suggestions. But outside of the main quest line I would not consider the others as a progression line more of a easy to understand mod guide, wooden armour is a tinkers construct thing hence it goes in the tinkers line progression has nothing to do with it, the book is merely showing you what you can do with that mod. I'll take some if your ideas into consideration.
