### ISSUE TITLE
World crash upon loading

### ISSUE THREAD

**Issue by Magicman9090** [WTFGeeks/Natural-Magic#83]
My Natural Magic world crashes consistently when a tempting to load it link to crash report:    http://paste.atlauncher.com/view/c7bbd3d9

**Comment by WTFGeeks** [comment]
This is a known forge issue and is pretty rare to happen I'v only come across it once in testing numerous amounts of worlds, until it is fixed all I can suggest is delete the village.dat file in your world file, that fixed it for me.
