### ISSUE TITLE
"I Feel Great!": can't tell what exact potions needed

### ISSUE THREAD

**Issue by Shurhaian** [WTFGeeks/Natural-Magic#84]
For the "I Feel Great!" potion-brewing quest, it's not apparent from the client's quest book what exact variety of potion is needed. The basic regen/fire res and basic splash healing potions don't satisfy it. With fire resistance, some Minecraft knowhow will tell you that the only viable upgrade is redstone for the long-duration potion - but there aren't any hints that that's also what you need for the regen, so one needs to guess, and potentially waste a ghast tear (which are cursed hard to find thanks to Lycanite's mobs in the Nether!) if they guess wrong and throw all potions the wrong way. For the instant health potions, they CAN'T be upgraded after turning them into splash potions, so it's that much more of a nuisance.

**Comment by WTFGeeks** [comment]
Potions currently in HQM do not show the type, I'v added them to the quest description in 0.7.2, Vanilla Nether spawning has also been upped while lycanites drastically reduced. update will be out soon.
