### ISSUE TITLE
game crach

### ISSUE THREAD

**Issue by Skyllian** [WTFGeeks/Natural-Magic#9]
my game crached when i placed a gravestone and typed on the stone

KEEP
OUT

ps. here is the crach report
http://openeye.openmods.info/crashes/c7837667efe94e890c0eb83659d1de39

**Comment by Skyllian** [comment]
got another one when i fished up my first fish.

**Comment by shadow1moon** [comment]
In accords to the fish, It crashes whenever I reel in a fishing rod.

**Comment by WTFGeeks** [comment]
Issues with fishing have been located and will be fixed in a version 0.6.1, expect the update in a few days.

**Comment by Skyllian** [comment]
thanks :) 

i really love the mod-pack you created !! btw.. maby a good idea to make a update vid.. 

keep up the good work !!
