### ISSUE TITLE
Diamond spawn at sea level

### ISSUE THREAD

**Issue by xobo3211** [WTFGeeks/Natural-Magic#92]
When playing the Natural Magic mudpack, I was exploring around and found an essence pool from AM2 at sea level. When I looked at it, I saw a diamond ore inside the pool. Any explanation for this? Can diamonds really spawn at sea level?
![2014-11-26_17 29 37](https://cloud.githubusercontent.com/assets/9968917/5209880/e73a0b36-7591-11e4-8418-e978cd6d008d.png)

**Comment by BronyfromOz** [comment]
Yeah Lewis upped the spawns for ores so you can find basically everything at any level.  Diamonds aren't end game in this pack.

**Comment by Leekit** [comment]
Not to mention that is Apatite Ore from Forestry.

**Comment by BronyfromOz** [comment]
Look carefully under the crosshair Leekit.
