### ISSUE TITLE
Blocklings causing crash in 0.7.2

### ISSUE THREAD

**Issue by Enolamron** [WTFGeeks/Natural-Magic#95]
http://pastebin.com/PDdFxxsh

I tried removing the blocklings mod but started getting client crash to desktop when logging in. Might of been something already on the server that was causing the crash. So I need to keep blocklings in for now and deal with the random crashes until I can figure out how to remove it.

This was the client crash after removing blocklings. Re-installing blocklings fixed it.
http://pastebin.com/VAVmDKuB

Edit: Thought I would point out the first crash was with no mods removed. I only tried removing the blocklings mod to stop the crashes but it caused a whole new issue removing it and I see you posted that the quest mod needs blocklings installed.

**Comment by WTFGeeks** [comment]
I'm going to need a little more information than this, what was you doing when the crashed happened? how often is the crash? Have you interacted with the blocklings mod in anyway? my only guess at the minute is judging by the crash log it mentions food, this might be to do with how they take some of the players health and hunger upon spawning. You could try disabling that in the Blocklings.cfg and see if it helps.

**Comment by Enolamron** [comment]
I personally haven't done anything with the mod. Before I tried removing the blocklings mod someone did have a pet but after I removed it and re-added it he lost the pet. I'm unsure if anyone else on the server has made one. I let the people know that were online not to mess with them but who knows. The crash seems completely random. Sometimes it will happen 3 times in 30 mins other time it will go for hours without a crash. I'll try B:"Player Damage"=false and post back if it crashes again.

**Comment by WTFGeeks** [comment]
ok cheers, looking on here http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2125932-blocklings-2-1-2-new-installer?page=49 some one had the same crash and it was to do with pacing a blockling and was advised to change that config option. I'll do some testing myself and see if I can get in contact with the dev taking it from there.

**Comment by Enolamron** [comment]
I doubt this has anything to do with the config change but while exploring I just got a structure gen crash. This was unexplored by anyone and the first time I have seen this crash.

http://pastebin.com/7vsQUzPj

I had to teleport out with Crystal Wings before the chunk loaded when I logged in. It crashed over and over once I logged in and it had loaded the chunk. Once I was away from the chunk no crashes. I couldn't tell what type of structure was trying to gen.

**Comment by WTFGeeks** [comment]
I have just released v0.7.2.1 I'm having a real hard time tracking down that issue, but I believe this update will stop it from happening again, although it will not resolve the affected area. Doom like dungeons was using a very old 1.7.2 way of adding blocks to the world, in most occasions this was fine but when they changed modded landscape it was having a problem as it didn't understand the code it was to be changing. For now it has been dropped from the pack and I'm going to speak with the developer.
