### ISSUE TITLE
0.7.2 map mod

### ISSUE THREAD

**Issue by Shyefox** [WTFGeeks/Natural-Magic#96]
In trying to update the pack with the map mod you have under recommended, it takes you to the site but the mod is no longer there. Any chance of getting a new map mod? Tried putting Rei's on it just for some manner of map, but for some reason it won't actually apply the Rei's in-game.

**Comment by WTFGeeks** [comment]
The recommended map mod is Opis which does now require a web download, I have updated journey maps web download link also as the dev has not updated his download location link.

**Comment by Shyefox** [comment]
Ah, thank you for clearing that up for me xD I'll re-install then with Opis instead of trying journey. Love the pack so far <3

**Comment by WTFGeeks** [comment]
No worries, glad you enjoy it :D
