### ISSUE TITLE
Cant download latest version (0.7.2.1)

### ISSUE THREAD

**Issue by RebelTamnatic** [WTFGeeks/Natural-Magic#97]
Hi there, when i go to download/ install the latest version, it gets to Scala and guava mods, it takes ages to try to download , then will freeze and does not progress past 5 mb. is there a way to get round this as i have tried everything, i have re installed AT launcher multiple times, i have tried to make new instances everytime with the same result. I have also updated then downgraded my java. If you could help would appreciate it.
Many Thanks Rebel_Tamnatic

**Comment by WTFGeeks** [comment]
I believe this is a ATLauncher issue not the pack itself, I have just done a few test downloads via the launcher and not had a problem, this thread mite help sounds like the same thing you have described - http://forums.atlauncher.com/thread-3790.html

**Comment by RebelTamnatic** [comment]
Thanks, i will read through this and i hope it will help :)
